## you most probably dont need to change these
tools: "config/tools.yaml"
## you probably need to change or comment/uncomment some of these
samples: "config/samples_test.tsv"
workdir: "WORKDIR"
resources: "RESOURCESDIR"
hisatindex: "HISAT2INDEXDIR"
## genome can be mm10 or hg38 ... mm10 for testdata
genome: "mm10"