## you most probably dont need to change these
tools: "config/tools.yaml"
## you probably need to change or comment/uncomment some of these
samples: "config/samples.tsv"
workdir: "WORKDIR"
resources: "RESOURCESDIR"
hisatindex: "HISAT2INDEXDIR"
## genome can be mm10 or hg38
genome: "mm10"
## uncomment and redefined scriptsdir if it is not the same as PIPELINE_HOME/worflow/scripts
# scripts: "scripts"