workdir: "WORKDIR"
samples: "WORKDIR/samples.tsv"
## genome can be mm10 or hg38
genome: "mm10"

#pre SNP calling filters
mapqfilter: "3"
# reads with this number or more insertions will be filtered out
ninsertionfilter: "1"

## you most probably dont need to change these
scriptsdir: "PIPELINE_HOME/workflow/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "PIPELINE_HOME/config/tools.yaml"
cluster: "PIPELINE_HOME/config/cluster.json"
hisatindexdir: "HISAT2INDEXDIR"
hisat_rna_strandness: "RF"
gtf:
  mm10: "/data/RBL_NCI/Wolin/mESC_slam_analysis/resources/mm10/mm10.v25.gtf"
  hg38: "/data/RBL_NCI/Wolin/mESC_slam_analysis/resources/hg38/hg38.v36.gtf"
htseqparams: "-f bam -r pos --stranded yes --additional-attr=gene_name"
